### ISSUE TITLE
SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'FBSimulatorControlKit')

### ISSUE THREAD

**Issue by selaysoysal** [badoo/ios-device-server#64]
Hello, 
I am trying to build the server. After I use the command  ./bootstrap.sh, I get an error. It says: error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'FBSimulatorControlKit')

** BUILD FAILED **

How do I fix this? Should I use older versions of Xcode? I use Xcode 10.3

**Comment by stereotype013** [comment]
@selaysoysal 
Hello, 
I have got such error, like you. You closed this issue, so you fix this problem or use any alternatives of this server? 
Thank you for your response

**Comment by fr0l** [comment]
Hi @selaysoysal @stereotype013 
Unfortunately ```fbsimctl``` utility is not anymore supported by FB team.

If you still rely on builds for ```fbsimctl``` you can build one using Xcode 10.3 from ```badoo``` branch in this repo https://github.com/fr0l/FBSimulatorControl/commits/badoo

the codebase there is frozen at 25th of April (the next commits were introducing ```idb``` tool).
There are some changes in order to support new devices and new iOS.

**Comment by stereotype013** [comment]
Hello, @fr0l! 
Thanks a lot for your help and fast answer.

**Comment by selaysoysal** [comment]
@stereotype013  sorry for late answer, 

I changed commit number to 0197d6d in ios-device-server-master/device-server/scripts/build_fbsimctl.sh. That worked but I get some other errors. I could not run it.

**Comment by fr0l** [comment]
@selaysoysal @stereotype013  if you find issues, i've noticed that fbsimctl and WDA should be compiled by same version of Xcode - i.e. 10.3

**Comment by selaysoysal** [comment]
@fr0l  I can compile both of them in same Xcode but, I still couldn't run this repo. I get this error now: 

/var/folders/vb/jvgk0jks25sdlbq6zgml03d80000gp/T/tmp.EvZwJbW9/WebDriverAgentLib/Categories/XCUIElement+FBUtilities.m:121:4: error: 
      messaging unqualified id [-Werror,-Wobjc-messaging-id]
  [[XCAXClient_iOS sharedClient] notifyWhenNoAnimationsAreActiveForApplication:self.a...
   ^
1 error generated.


** TEST BUILD FAILED **


The following build commands failed:

CompileC /var/folders/vb/jvgk0jks25sdlbq6zgml03d80000gp/T/tmp.EvZwJbW9/build/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphonesimulator/WebDriverAgentLib.build/Objects-normal/x86_64/XCUIElement+FBUtilities.o /var/folders/vb/jvgk0jks25sdlbq6zgml03d80000gp/T/tmp.EvZwJbW9/WebDriverAgentLib/Categories/XCUIElement+FBUtilities.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
